In [1]:
import pandas as pd
import numpy as np

In [2]:
DATA_PATH = "../data/cleaned_ntb_only_en_scd.pkl"

In [3]:
df = pd.read_pickle(DATA_PATH)
df

,cell-type,source,title,tag
0,code,import pandas as pd import numpy as np import ...,0-9-try-better-parameters-better-score.ipynb,regression
1,markdown,try to overfit more pls upvote if you fork lik...,0-9-try-better-parameters-better-score.ipynb,regression
2,markdown,sub1 0 869,0-9-try-better-parameters-better-score.ipynb,regression
3,markdown,credit very simple code with score 0 886 by ay...,0-9-try-better-parameters-better-score.ipynb,regression
4,code,import pandas as pd import numpy as np from sk...,0-9-try-better-parameters-better-score.ipynb,regression
...,...,...,...,...
344966,code,"POI_data = gpd.read_file(""../input/geospatial...",your-first-map.ipynb,reinforcement learning
344967,markdown,next we create a map from all four geodatafram...,your-first-map.ipynb,reinforcement learning
344968,code,"ax = counties.plot(figsize=(10,10), color='no...",your-first-map.ipynb,reinforcement learning
344969,markdown,it looks like the northeastern part of the sta...,your-first-map.ipynb,reinforcement learning
344970,markdown,have questions or comments visit the course di...,your-first-map.ipynb,reinforcement learning

In [4]:
for i in df.columns:
    df[i].fillna(' ', inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 332605 entries, 0 to 344970
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cell-type  332605 non-null  object
 1   source     332605 non-null  object
 2   title      332605 non-null  object
 3   tag        332605 non-null  object
dtypes: object(4)
memory usage: 12.7+ MB

In [6]:
df_tansf = pd.DataFrame(columns=['md_pair','cd_pair','title','tag'])
df_tansf

Empty DataFrame
Columns: [md_pair, cd_pair, title, tag]
Index: []

In [7]:
def transf_only_cd_ntb(old_data,new_data,counter):
    for i in old_data.index :
        if (len(str(old_data.loc[i]['source']).split())) < 256 and (len(str(old_data.loc[i]['source']).split())) > 3:
            new_data.loc[len(new_data)] = [" ",str(old_data.loc[i]['source']),str(old_data.loc[i]['title']),str(old_data.loc[i]['tag'])]
        else:
            counter += 1
    
    return counter

In [8]:
def transf_only_md_ntb(old_data,new_data,counter):
    for i in old_data.index :
        if (len(str(old_data.loc[i]['source']).split())) < 256 and (len(str(old_data.loc[i]['source']).split())) > 3:
            new_data.loc[len(new_data)] = [str(old_data.loc[i]['source'])," ",str(old_data.loc[i]['title']),str(old_data.loc[i]['tag'])]
        else:
            counter += 1
    
    return counter

In [84]:
def construct_pairs(old_data,new_data,counter):
    rgp_md = ''
    index = 0 

    while(old_data.iloc[index]['cell-type'] == "markdown") and index < len(old_data):
            rgp_md += str(old_data.iloc[index]['source']) + " "
            index +=1
            print("index1 here:",index)
    
    while(old_data.iloc[index]['cell-type'] == "code") and index < len(old_data):
            new_data.loc[len(new_data)] = [rgp_md,str(old_data.iloc[index]['source']),str(old_data.iloc[index]['title']),str(old_data.iloc[index]['tag'])]
            index +=1
            print("index2 here:",index)
            
    

    counter += index
    print(counter)

    if counter < len(old_data):
                construct_pairs(old_data.loc[index+1:],new_data,counter)

In [10]:
def transf_ntb(old_data,new_data):
    if old_data.iloc[0]['cell-type'] == "code":
        new_data.loc[len(new_data)] = [" ",str(old_data.loc[0]['source']),str(old_data.loc[0]['title']),str(old_data.loc[0]['tag'])]
        transf_ntb(old_data[1:],new_data)
    else :
        construct_pairs(old_data,new_data,0)

In [11]:
"""
List_1 = []
List_2 = []
counter_1 = 0
counter_2 = 0
full_text_md = ''
full_text_cd = ''
groups = df.groupby('title')
List_ntb = np.unique(df['title'].tolist()).tolist()
for ntb in List_ntb :
    data_ntb = df[df['title'] == ntb] 
    for i in data_ntb.index:
            if data_ntb.loc[i]['cell-type'] == "markdown":
                full_text_md += str(data_ntb.loc[i]['source'])
            else :
                full_text_cd += str(data_ntb.loc[i]['source'])
    
    if full_text_md == '' :
        full_text_md = ''
        full_text_cd = ''
        counter_1 += transf_only_cd_ntb(data_ntb,df_tansf,counter_1)
        List_1 .append(ntb)

    elif full_text_cd == '':
        full_text_md = ''
        full_text_cd = ''
        counter_2 += transf_only_md_ntb(data_ntb,df_tansf,counter_2)
        List_2 .append(ntb)

    else :
        full_text_md = full_text_cd = ''
"""

'\nList_1 = []\nList_2 = []\ncounter_1 = 0\ncounter_2 = 0\nfull_text_md = \'\'\nfull_text_cd = \'\'\ngroups = df.groupby(\'title\')\nList_ntb = np.unique(df[\'title\'].tolist()).tolist()\nfor ntb in List_ntb :\n    data_ntb = df[df[\'title\'] == ntb] \n    for i in data_ntb.index:\n            if data_ntb.loc[i][\'cell-type\'] == "markdown":\n                full_text_md += str(data_ntb.loc[i][\'source\'])\n            else :\n                full_text_cd += str(data_ntb.loc[i][\'source\'])\n    \n    if full_text_md == \'\' :\n        full_text_md = \'\'\n        full_text_cd = \'\'\n        counter_1 += transf_only_cd_ntb(data_ntb,df_tansf,counter_1)\n        List_1 .append(ntb)\n\n    elif full_text_cd == \'\':\n        full_text_md = \'\'\n        full_text_cd = \'\'\n        counter_2 += transf_only_md_ntb(data_ntb,df_tansf,counter_2)\n        List_2 .append(ntb)\n\n    else :\n        full_text_md = full_text_cd = \'\'\n'

In [12]:
#List_1

In [13]:
#List_2

windows-yolov5l.ipynb MUST BE DELETED chineesee ntb

In [14]:
df_tansf

Empty DataFrame
Columns: [md_pair, cd_pair, title, tag]
Index: []

In [15]:
df

,cell-type,source,title,tag
0,code,import pandas as pd import numpy as np import ...,0-9-try-better-parameters-better-score.ipynb,regression
1,markdown,try to overfit more pls upvote if you fork lik...,0-9-try-better-parameters-better-score.ipynb,regression
2,markdown,sub1 0 869,0-9-try-better-parameters-better-score.ipynb,regression
3,markdown,credit very simple code with score 0 886 by ay...,0-9-try-better-parameters-better-score.ipynb,regression
4,code,import pandas as pd import numpy as np from sk...,0-9-try-better-parameters-better-score.ipynb,regression
...,...,...,...,...
344966,code,"POI_data = gpd.read_file(""../input/geospatial...",your-first-map.ipynb,reinforcement learning
344967,markdown,next we create a map from all four geodatafram...,your-first-map.ipynb,reinforcement learning
344968,code,"ax = counties.plot(figsize=(10,10), color='no...",your-first-map.ipynb,reinforcement learning
344969,markdown,it looks like the northeastern part of the sta...,your-first-map.ipynb,reinforcement learning
344970,markdown,have questions or comments visit the course di...,your-first-map.ipynb,reinforcement learning

In [16]:
df.loc[1:]

,cell-type,source,title,tag
1,markdown,try to overfit more pls upvote if you fork lik...,0-9-try-better-parameters-better-score.ipynb,regression
2,markdown,sub1 0 869,0-9-try-better-parameters-better-score.ipynb,regression
3,markdown,credit very simple code with score 0 886 by ay...,0-9-try-better-parameters-better-score.ipynb,regression
4,code,import pandas as pd import numpy as np from sk...,0-9-try-better-parameters-better-score.ipynb,regression
5,markdown,sub2 0 860,0-9-try-better-parameters-better-score.ipynb,regression
...,...,...,...,...
344966,code,"POI_data = gpd.read_file(""../input/geospatial...",your-first-map.ipynb,reinforcement learning
344967,markdown,next we create a map from all four geodatafram...,your-first-map.ipynb,reinforcement learning
344968,code,"ax = counties.plot(figsize=(10,10), color='no...",your-first-map.ipynb,reinforcement learning
344969,markdown,it looks like the northeastern part of the sta...,your-first-map.ipynb,reinforcement learning
344970,markdown,have questions or comments visit the course di...,your-first-map.ipynb,reinforcement learning

In [81]:
testing_data = df[1:20]
testing_data

,cell-type,source,title,tag
1,markdown,try to overfit more pls upvote if you fork lik...,0-9-try-better-parameters-better-score.ipynb,regression
2,markdown,sub1 0 869,0-9-try-better-parameters-better-score.ipynb,regression
3,markdown,credit very simple code with score 0 886 by ay...,0-9-try-better-parameters-better-score.ipynb,regression
4,code,import pandas as pd import numpy as np from sk...,0-9-try-better-parameters-better-score.ipynb,regression
5,markdown,sub2 0 860,0-9-try-better-parameters-better-score.ipynb,regression
6,markdown,credit tokenizer training tfidf ridge lb 0 860...,0-9-try-better-parameters-better-score.ipynb,regression
7,code,import numpy as np import pandas as pd import ...,0-9-try-better-parameters-better-score.ipynb,regression
8,markdown,sub3 0 858,0-9-try-better-parameters-better-score.ipynb,regression
9,markdown,credit rapids tfidf linear model ensemble by z...,0-9-try-better-parameters-better-score.ipynb,regression
10,code,import pandas as pd import numpy as np from tq...,0-9-try-better-parameters-better-score.ipynb,regression
11,markdown,sub4:0 873,0-9-try-better-parameters-better-score.ipynb,regression
12,code,from sklearn.linear_model import LinearRegress...,0-9-try-better-parameters-better-score.ipynb,regression
13,markdown,you can try to modify the parameters to get a ...,0-9-try-better-parameters-better-score.ipynb,regression
14,code,"data = pd.read_csv(""./submission1.csv"",index_c...",0-9-try-better-parameters-better-score.ipynb,regression
15,code,,0-9-try-better-parameters-better-score.ipynb,regression
16,code,"for f in ['score1','score2','score3']: fo...",0-9-try-better-parameters-better-score.ipynb,regression
17,code,"data[""score""] = .66*data[""score1""] + .66*data...",0-9-try-better-parameters-better-score.ipynb,regression
18,markdown,for even more overfit,0-9-try-better-parameters-better-score.ipynb,regression
19,markdown,credit scaling for jigsaw ensemble by chryzal ...,0-9-try-better-parameters-better-score.ipynb,regression

In [85]:
df_tansf_test = pd.DataFrame(columns=['md_pair','cd_pair','title','tag'])
df_tansf_test

Empty DataFrame
Columns: [md_pair, cd_pair, title, tag]
Index: []

In [86]:
transf_ntb(testing_data,df_tansf_test)

index1 here: 1
index1 here: 2
index1 here: 3
index2 here: 4
4
index1 here: 1
index1 here: 2
index2 here: 3
7
index1 here: 1
index1 here: 2
index2 here: 3
10
index1 here: 1
index1 here: 2
index2 here: 3
13
index1 here: 1
index1 here: 2
index2 here: 3
16

In [79]:
df_tansf_test

,md_pair,cd_pair,title,tag
0,try to overfit more pls upvote if you fork lik...,import pandas as pd import numpy as np from sk...,0-9-try-better-parameters-better-score.ipynb,regression
1,sub2 0 860 credit tokenizer training tfidf rid...,import numpy as np import pandas as pd import ...,0-9-try-better-parameters-better-score.ipynb,regression
2,sub2 0 860 credit tokenizer training tfidf rid...,import numpy as np import pandas as pd import ...,0-9-try-better-parameters-better-score.ipynb,regression
3,sub2 0 860 credit tokenizer training tfidf rid...,import numpy as np import pandas as pd import ...,0-9-try-better-parameters-better-score.ipynb,regression
4,sub2 0 860 credit tokenizer training tfidf rid...,import numpy as np import pandas as pd import ...,0-9-try-better-parameters-better-score.ipynb,regression

In [23]:
for i in df_tansf_test.index:
    print(df_tansf_test.loc[i]['md_pair']+'\n')

try to overfit more pls upvote if you fork liked it thanks sub1 0 869 credit very simple code with score 0 886 by ayahm barish

sub2 0 860 credit tokenizer training tfidf ridge lb 0 860 by adriano passos

sub2 0 860 credit tokenizer training tfidf ridge lb 0 860 by adriano passos

sub2 0 860 credit tokenizer training tfidf ridge lb 0 860 by adriano passos

sub2 0 860 credit tokenizer training tfidf ridge lb 0 860 by adriano passos